training:
  stage1:
    model_name: Qwen/Qwen2.5-7B-Instruct
    batch_size: 1
    context_length_min: 4000
    context_length_max: 32000
    reg_weight: 0.2
    lr: 0.08
    dataset_format: duo_data
    steps: 2000
    context_lengths_num_intervals: 100
    output_dir: patterns/qwen/stage1-lr=0.08-reg=0.2-ctx=4000_32000-data=duo_data
    exp_name: qwen-stage1-lr=0.08-reg=0.2-ctx=4000_32000-data=duo_data
  stage2:
    model_name: Qwen/Qwen2.5-7B-Instruct
    batch_size: 1
    context_length_min: 4000
    context_length_max: 32000
    reg_weight: 0.
    lr: 0.02
    dataset_format: duo_data
    steps: 200
    context_lengths_num_intervals: 100
    align: 32
    ratio: 0.6
    stage1_rst_path: patterns/qwen/stage1-lr=0.08-reg=0.2-ctx=4000_32000-data=duo_data
    output_dir: patterns/qwen/stage2-lr=0.02-reg=0-ctx=4000_32000-data=duo_data
    exp_name: qwen-stage2-lr=0.02-reg=0-ctx=4000_32000-data=duo_data-align=32-ratio=0.6

